apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: {{ .Values.name }}
        image: 711387102542.dkr.ecr.us-east-1.amazonaws.com/frontend-ui:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
      type: LoadBalancer
      nodeSelector: {{ toJson .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toJson .Values.tolerations | nindent 8 }}
      affinity: {{ toJson .Values.affinity | nindent 8 }}
