apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: fargate-applications
  labels:
    app: {{ .Chart.Name }}
    tier: "frontend"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "HTTP"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Chart.Name }}
    tier: "frontend"
