name: frontend
replicaCount: 1

image:
  repository: frontend-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [] # Example:
  # tls:
  #   - secretName: frontend-tls
  #     hosts:
  #       - frontend.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
