apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: backend-api
          image: 711387102542.dkr.ecr.us-east-1.amazonaws.com/backend-api:latest
          ports:
            - containerPort: 3000
      type: LoadBalancer
