apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: {{ .values.image.repository }}:{{ .values.image.tag }}
          ports:
            - containerPort: 3000
