name: Deploy with Submodules

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' # Clone submodules recursively
          fetch-depth: 0          # Fetch all history for accurate submodule checkout

      - name: Build and Deploy
        run: |
          # Your build and deployment commands go here
          echo "Building and deploying..."
          
          # Example: Deploy backend
          docker build -t your-ecr-repo/backend-api:latest ./backend-api
          docker push your-ecr-repo/backend-api:latest
          
          # Example: Deploy frontend
          docker build -t your-ecr-repo/frontend-ui:latest ./frontend-ui
          docker push your-ecr-repo/frontend-ui:latest

          # Example: Deploy to Kubernetes using Helm
          helm upgrade --install backend-api ./deployment/backend \
            --set image.repository=your-ecr-repo/backend-api \
            --set image.tag=latest
          helm upgrade --install frontend-ui ./deployment/frontend \
            --set image.repository=your-ecr-repo/frontend-ui \
            --set image.tag=latest