name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up AWS credentials for Terraform and kubectl
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 2: Verify EKS cluster exists
      - name: Verify EKS Cluster
        id: verify-cluster
        run: |
          CLUSTER_EXISTS=$(aws eks describe-cluster --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --query "cluster.status" --output text || echo "NOT_FOUND")
          echo "cluster_exists=$CLUSTER_EXISTS" >> $GITHUB_ENV

      # Step 3: Setup terraform
      - name: Set up Terraform
        if: env.cluster_exists == 'NOT_FOUND'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      # Step 4: Terraform Init
      - name: Terraform Init
        if: env.cluster_exists == 'NOT_FOUND'
        run: terraform init
        working-directory: ./terraform/eks-cluster
      
      # Step 5: Create EKS cluster if not found
      - name: Terraform Apply
        if: env.cluster_exists == 'NOT_FOUND'
        run: terraform apply -auto-approve
        working-directory: ./terraform/eks-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 6: Set up kubectl to interact with EKS
      - name: Set up kubectl for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      # Step 7: Deploy backend and frontend to EKS
      - name: Deploy to EKS - Backend
        run: kubectl apply -f ./deployment/backend/deployment.yaml
      - name: Deploy to EKS - Frontend
        run: kubectl apply -f ./deployment/frontend/deployment.yaml