name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify EKS Cluster
        id: verify-cluster
        run: |
          CLUSTER_STATUS=$(aws eks describe-cluster --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --query "cluster.status" --output text || echo "NOT_FOUND")
          echo "CLUSTER_EXISTS=$CLUSTER_STATUS" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/eks-cluster
        env:
          TF_LOG: DEBUG  # Enable detailed logging

      - name: Terraform Apply or Update
        run: |
          if [[ "$CLUSTER_EXISTS" == "NOT_FOUND" ]]; then
            terraform apply -auto-approve
          else
            terraform apply -refresh-only -auto-approve
          fi
        working-directory: ./terraform/eks-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_LOG: DEBUG  # Enable detailed logging

      - name: Make set_env_vars.sh executable
        run: chmod +x ./set_env_vars.sh

      - name: Set environment variables from Terraform outputs
        run: ./set_env_vars.sh

      - name: Set up kubectl for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS - Backend
        run: kubectl apply -f ./deployment/backend/templates/deployment.yaml

      - name: Deploy to EKS - Frontend
        run: kubectl apply -f ./deployment/frontend/templates/deployment.yaml